### ISSUE TITLE
ValueError: The histogram is empty, please file a bug report.

### ISSUE THREAD

**Issue by leolin65** [pankajmishra000/VT-ADL#1]
Traceback (most recent call last):
  File "D:\Code\VT-ADL-master\train.py", line 85, in <module>
    writer.add_histogram('Vectors', vector)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\utils\tensorboard\writer.py", line 433, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\utils\tensorboard\summary.py", line 315, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\utils\tensorboard\summary.py", line 353, in make_histogram
    raise ValueError('The histogram is empty, please file a bug report.')
ValueError: The histogram is empty, please file a bug report.

**Comment by pankajmishra000** [comment]
the problem is that you are using very few Gaussian's for the GMM network. Try to increase the value of COEF=150, in mdn1.py (line 15).

With the underrepresented Gaussians, there is a problem of gradient underflow. So we get NaN, hence the tensorboard throws the above error.

**Comment by dulishu1999** [comment]
the methold did not solve the problem
