### ISSUE TITLE
the problem of training，the error is reported as follows

### ISSUE THREAD

**Issue by dulishu1999** [pankajmishra000/VT-ADL#12]
loss3  : 977.2217407226562
 loss3  : 953.9542846679688
 loss3  : 977.0262451171875
 loss3  : 968.5617065429688
 loss3  : 951.572509765625
 loss3  : 965.5928955078125
 loss3  : 955.4605102539062
 loss3  : 961.7124633789062
 loss3  : 965.6633911132812
 loss3  : 955.3429565429688
 loss3  : 946.2571411132812
 loss3  : 961.953125
 loss3  : 945.2177734375
 loss3  : 964.3775024414062
 loss3  : nan
Traceback (most recent call last):
  File "D:\DeepLearning\VT-ADL-master\train.py", line 87, in <module>
    writer.add_histogram('Vectors', vector)
  File "C:\Users\24114\anaconda3\envs\vt_adl\lib\site-packages\torch\utils\tensorboard\writer.py", line 485, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime
  File "C:\Users\24114\anaconda3\envs\vt_adl\lib\site-packages\torch\utils\tensorboard\summary.py", line 355, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "C:\Users\24114\anaconda3\envs\vt_adl\lib\site-packages\torch\utils\tensorboard\summary.py", line 399, in make_histogram
    raise ValueError("The histogram is empty, please file a bug report.")
**ValueError: The histogram is empty, please file a bug report.**

**Comment by pankajmishra000** [comment]
multiply with 1e-5 with the logvar value. They are very high. so you have to modify line 39 of mdn1.py as
sigma_sq = F.softplus(self.sigma_sq(x)).view(x.size(0),x.size(1),self.in_features, -1) *1e-5 # logvar
