### ISSUE TITLE
 histogram is empty

### ISSUE THREAD

**Issue by Y-JIE-CREATOR** [pankajmishra000/VT-ADL#8]
I have selected several “product ” to run. All of them have the following problems that cause the program to end abnormally：

Traceback (most recent call last):
  File "train.py", line 85, in <module>
    writer.add_histogram('Vectors', vector)
  File "/home/wxy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 441, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime)
  File "/home/wxy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/tensorboard/summary.py", line 320, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "/home/wxy/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/tensorboard/summary.py", line 358, in make_histogram
    raise ValueError('The histogram is empty, please file a bug report.')
ValueError: The histogram is empty, please file a bug report.
(torch) wxy@wxy-MS-7B73:~/LYJ/VT-ADL-master$

**Comment by pankajmishra000** [comment]
refer to this- https://github.com/pankajmishra000/VT-ADL/issues/1
